name: dotnet build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - run: |
          dotnet build "AdeptiScanner ZZZ.sln" -c Release
          mkdir AdeptiScanner_ZZZ
          mv "AdeptiScanner ZZZ/bin/Release/net8.0-windows" AdeptiScanner_ZZZ/AdeptiScanner_ZZZ
      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parase --short HEAD)" >> $GITHUB_OUTPUT
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AdeptiScanner_ZZZ.${{ steps.sha.outputs.sha }}
          path: AdeptiScanner_ZZZ
